# Generated by Django 3.2.4 on 2021-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_post_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
